name: Test on push

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: python -m unittest discover -s GameRecommender/api/test -p '*_test.py'

      
